.PHONY: RiseCraft-resource-pack.zip
RiseCraft-resource-pack.zip:
	-rm -rf RiseCraft-resource-pack.zip
	zip -r RiseCraft-resource-pack.zip assets pack.mcmeta pack.png LICENSE.txt imgs fabricskyboxes
	shasum -a 1 RiseCraft-resource-pack.zip